{% set name = "h5glance" %}
{% set org = "European-XFEL" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 65bfe1d52f4c5e5356fcba86c558e82d24cc73dddd71c99b434a09c15cf94a71

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - h5glance = {{ name }}.terminal:main
    - h5glance-html = {{ name }}.html_cli:main

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - h5py >=2.10
    - htmlgen

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - {{ name }}
  commands:
    - pip check
    - h5glance --version | grep {{ version }}
    - h5glance-html -h

about:
  home: https://github.com/European-XFEL/h5glance
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Lets you explore HDF5 files in the terminal or an HTML interface.
  description: Lets you explore HDF5 files in the terminal or an HTML interface.
  doc_url: https://github.com/European-XFEL/h5glance
  dev_url: https://github.com/European-XFEL/h5glance

extra:
  recipe-maintainers:
    - tdegeus
